---
title: "Analisis de los coches (mtcars)"
author: "Ramon Ceballos"
date: "11/2/2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
use_python("../../../../../../Desktop/Python 3.9/Python 3.9 (64-bit).lnk")
```

# **Análisis de los coches (mtcars)**

## 1. Carga de datos

Vamos a trabajar con Python.

Importamos las librerías que vamos a usar en el análisis y cargamos los datos del dataset "mtcars" presente en ggplot.

```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from ggplot import mtcars
```

Vemos si se han cargado los datos correctamente.

```{python}
data = mtcars
print(data.head(4))
```

## 2. Medidas de centralización

Vemos que el índice se asigna por números que pone Python. Vamos a asignar el índice según el nombre del modelo del coche.

```{python}
data.index = data["name"]
```

A continuación hago la **media** para cada una de las columnas numéricas.

```{python}
print(data.mean())
```

También se puede hacer la media por filas, aunque en este caso no tenga sentido.

```{python}
print(data.mean(axis=1))
```

La mediana de la distribución para cada columna sería:

```{python}
print(data.median())
```

La moda sería:

```{python}
print(data.mode())
```


## 3. Medidas vs Distribuciones

La media y la mediana no siempre tienen que coincidir, y esto a su vez depende del sesgo de la distribución. Cuando la distribución es simétrica la mediana y la media coinciden. Cuando el sesgo es positivo o negativo, no coincidirán.

Genero unos datos aleatorios segun una normal y represento un plot de la función de densidad de dichos datos. A su vez, le añado una línea que coincida con la media y la mediana.

```{python}
norm_data = pd.DataFrame(np.random.normal(size=10000))

norm_data.plot(kind="density", figsize=(7,7))

plt.vlines(norm_data.mean(), ymin=0, ymax=0.5, linewidth=6.0, color="green")

plt.vlines(norm_data.median(), ymin=0, ymax=0.5, linewidth=2.0, color="red")

plt.show()

```

Vemos que la distribución es simétrica ya que la media y la mediana se superponen.

Limpio la figura con "plt.clf()" y represento unos datos de distribución exponencial de la misma forma que antes.

```{python}
skewed_data = pd.DataFrame(np.random.exponential(size=10000))

skewed_data.plot(kind="density", figsize=(7,7))

plt.vlines(skewed_data.mean(), ymin=0, ymax=0.7, linewidth=6.0, color="green")

plt.vlines(skewed_data.median(), ymin=0, ymax=0.7, linewidth=2.0, color="red")

plt.xlim(-2,5)

plt.show()
```

Se observa que hay un sesgo positivo (asimetría hacia la dcha), y la mediana es más pequeña que la media.

Ahora vamos a generar una distribución normal de 50 datos (norm_data) con una serie de outliers (outliers) que siguen una distribución normal con $\mu = 15$. Juntamos ambos datos en un Data Frame mediante np.concatenate, y para indicar que se haga por columnas se pone axis=0. 

```{python}
norm_data = np.random.normal(size=50)
outliers = np.random.normal(15,size=3)

combined_data = pd.DataFrame(np.concatenate((norm_data,outliers),axis=0))

combined_data.plot(kind="density", figsize=(7,7))

plt.vlines(combined_data.mean(), ymin=0, ymax=0.23, linewidth=6.0, color="green")

plt.vlines(combined_data.median(), ymin=0, ymax=0.23, linewidth=2.0, color="red")

plt.xlim(-10,20)

plt.show()
```

Ahora la media aparece desplaza a la dcha, indicando la existencia de un sesgo. Esto se debe a los outliers que hemos incorporado. La mediana, por tanto, es más robusta que la media debido a que se resiente menos frente a la presencia de outliers. La media en cambio es muy sensible.

Vamos a investigar si dentro del dataset de mtcars, la variable mpg (millas por galón) está sesgada o no.

```{python}
data_mpg = data [["mpg"]]

data_mpg.plot(kind="density", title="Distribucion para las millas por galon")

plt.vlines(data_mpg.mean(),
color="green", linewidth=6,
ymin=0, ymax=0.07)

plt.vlines(data_mpg.median(),
color="red", linewidth=2,
ymin=0, ymax=0.07)

plt.show()
```

Vemos que la media se encuentra desplazada ligeramente a la derecha, lo cual indica que hay un ligero sesgo positivo.

Para al potencia (hp) lo desarrollaríamos de forma análoga.

```{python}
data_hp = data [["hp"]]

data_hp.plot(kind="density", title="Distribucion para la potencia")

plt.vlines(data_hp.mean(),
color="green", linewidth=6,
ymin=0, ymax=0.006)

plt.vlines(data_hp.median(),
color="red", linewidth=2,
ymin=0, ymax=0.006)

plt.show()
```

También presenta un sesgo positivo la distribución de la variable de la potencia.


## 4. Medidas de dispersión

Estos estadísticos permiten estudiar la variación (diversidad) de los datos, mientras que las medidas de centralización dan una idea del valor más típico.

La dispersión se puede medir a través del **rango**. En este caso lo hacemos para las millas por galón.

```{python}
rang = max(data["mpg"])-min(data["mpg"])
print(rang)
```

Para poder describir la disepersión de una variable se emplean cinco percentiles distintos (five nums) que son: **mínmo, primer cuartil, mediana, tercer cuartil y el máximo**.

```{python}
five_nums = [data["mpg"].quantile(0),
         data["mpg"].quantile(0.25),
         data["mpg"].quantile(0.5),
         data["mpg"].quantile(0.75),
         data["mpg"].quantile(1)]

print(five_nums)
```

Estos five nums aparecen al emplear la función describe() sobre la variable de estudio.

```{python}
print(data["mpg"].describe())
```

Para obtener el rango intercuartílico (IQR), se hace lo siguiente:

```{python}
rang_int = data["mpg"].quantile(0.75)-data["mpg"].quantile(0.25)
print(rang_int)
```

Ahora vamos a representar graficamente los datos estadísticos de medidas de dispersión.

Empleamos un boxplot. Vamos a colocar cinco textos para diversos estadísticos.

```{python}
plt.clf()

data.boxplot(column = "mpg", return_type="axes",
figsize=(5,5))

plt.text(0.7, y = data["mpg"].quantile(0.25),
s = "Primer cuartil")

plt.text(0.75, y = data["mpg"].quantile(0.5),
s = "Mediana")

plt.text(0.7, y = data["mpg"].quantile(0.75),
s = "Tercer cuartil")

plt.text(0.85, y = data["mpg"].quantile(0),
s = "Minimo")

plt.text(0.85, y = data["mpg"].quantile(1),
s = "Maximo")

plt.text(x=0.65, y=data["mpg"].quantile(0.5),
s="IQR", rotation=90,
size=20)

plt.show()
```

La **varianza y la desviación típica** son los estadísticos estrellas para determinar la dispersión de una variable.

```{python}
print(data["mpg"].var())

print(data["mpg"].std())
```

Tanto la varianza como la desviación estándar son valores que proceden de la media, y esto significa que son medidas estadísticas muy influenciables a través de la curtosis y el sesgo de una distribución.

Debido a esto existe una tercera medida para el estudio de la dispersión de los datos. Es la **desviación mediana absoluta** (mad).

Para el cálculo de "mad" se resta cada valor contenido en la variable su mediana, dando el valor final en valor absoluto. Después se multiplica por el parámetro **k** que vale 1.4826. Este valor es más resistente a los outliers.

```{python}
mad = abs(data["mpg"]-data["mpg"].median())

k = 1.4826

print(mad.median()*k)
```


## 5. Medidas de forma de la distribución

En este apartado nos interesan dos estadísticos: el **sesgo** de la distribución y el coeficiente de **curtosis**.

El sesgo da información acerca de la simetría de la distribución, mientras que la curtosis da información sobre lo picuda que es la distribución (). Este coeficiente de curtosis indica la cantidad de datos que hay cercanos a la media, de manera que a mayor grado de curtosis, más escarpada (o apuntada) será la forma de la curva.

Son estadístico que nos da una idea de como se distribuyen los datos a lo largo de la distribución.

Para calcular el sesgo se emplea: ".skew()" en python.

Para calcular la curtosis se emplea: ".kurt()" en python.

```{python}
print(data["mpg"].skew())
print(data["mpg"].kurt())
```

Se observa que el sesgo es ligeramente positivo, los datos están tirando hacia la derecha. Mientras, la curtosis está cercana a cero por lo que no existe un alto grado de escarpamiento para la curva (poco pincho).

Ahora vamos a crear datos en base a distintas distribuciones y las vamos a representar, para también calcularle la curtosis y el sesgo.

```{python}
norm =np.random.normal(size = 100000)

skew_data = np.concatenate((np.random.normal(size=35000)+2,np.random.exponential(size=65000)), axis=0)

unif = np.random.uniform(-2,2,size = 100000)

peak = np.concatenate((np.random.exponential(size=50000),
np.random.exponential(size=50000)*(-1)),
axis = 0)

data = pd.DataFrame({
"normal":norm,
"skew":skew_data,
"unif":unif,
"peak":peak
})


plt.clf()
data.plot(kind="density", figsize=(7,7),xlim= (-5,5))

plt.show()

print("Normal, Sesgo = %f, Curtosis = %f" %(data["normal"].skew(), data["normal"].kurt()))

print("Normal+Exp, Sesgo = %f, Curtosis = %f" %(data["skew"].skew(), data["skew"].kurt()))

print("Uniforme, Sesgo = %f, Curtosis = %f" %(data["unif"].skew(), data["unif"].kurt()))

print("Suma de exponenciales, Sesgo = %f, Curtosis = %f" %(data["peak"].skew(), data["peak"].kurt()))
```



















